version: '3'

services:

  frontend:
    build: ./
    entrypoint: ./.docker/entrypoint.sh
    container_name: mfc-desafio2-frontend
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
